// TYPES
const LOGIN = 'LOGIN';
const STATISTIC_DATA = 'STATISTIC_DATA';
const STYLES_LIST = 'STYLES_LIST';
const FEEDS_LIST = 'FEEDS_LIST';
const USERS_LIST = 'USERS_LIST';
const SETTINGS_LIST = 'SETTINGS_LIST';
const SETTING_CREATE_UPDATE = 'SETTING_CREATE_UPDATE';
const ADD_STYLE = 'ADD_STYLE';
const ADD_USER = 'ADD_USER';
const ADD_POST = 'ADD_POST';
const EDIT_USER = 'EDIT_USER';
const EDIT_STYLE = 'EDIT_STYLE';
const REMOVE_STYLE = 'REMOVE_STYLE';
const DELETE_USER = 'DELETE_USER';
const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
const UPDATE_POST = 'UPDATE_POST';
const DELETE_VIDEO = 'DELETE_VIDEO';
const DELETE_PHOTO = 'DELETE_PHOTO';

// EVENTS
const LOGIN_EVENT = 'LOGIN_EVENT';
const STATISTIC_DATA_EVENT = 'STATISTIC_DATA_EVENT';
const STYLES_LIST_EVENT = 'STYLES_LIST_EVENT';
const FEEDS_LIST_EVENT = 'FEEDS_LIST_EVENT';
const USERS_LIST_EVENT = 'USERS_LIST_EVENT';
const SETTINGS_LIST_EVENT = 'SETTINGS_LIST_EVENT';
const SETTING_CREATE_UPDATE_EVENT = 'SETTING_CREATE_UPDATE_EVENT';
const ADD_STYLE_EVENT = 'ADD_STYLE_EVENT';
const ADD_USER_EVENT = 'ADD_USER_EVENT';
const ADD_POST_EVENT = 'ADD_POST_EVENT';
const EDIT_STYLE_EVENT = 'EDIT_STYLE_EVENT';
const EDIT_USER_EVENT = 'EDIT_USER_EVENT';
const REMOVE_STYLE_EVENT = 'REMOVE_STYLE_EVENT';
const DELETE_USER_EVENT = 'DELETE_USER_EVENT';
const UPDATE_USER_DATA_EVENT = 'UPDATE_USER_DATA_EVENT';
const UPDATE_POST_EVENT = 'UPDATE_POST_EVENT';
const DELETE_VIDEO_EVENT = 'DELETE_VIDEO_EVENT';
const DELETE_PHOTO_EVENT = 'DELETE_PHOTO_EVENT';

export {
  STYLES_LIST, USERS_LIST, LOGIN, REMOVE_STYLE, ADD_STYLE, ADD_USER, EDIT_STYLE, DELETE_USER, UPDATE_USER_DATA,
  FEEDS_LIST, EDIT_USER, ADD_POST, DELETE_PHOTO, DELETE_VIDEO, UPDATE_POST, STATISTIC_DATA, SETTINGS_LIST,
  SETTING_CREATE_UPDATE
}

export {
  STYLES_LIST_EVENT, USERS_LIST_EVENT, LOGIN_EVENT, ADD_STYLE_EVENT, ADD_USER_EVENT, EDIT_STYLE_EVENT,
  REMOVE_STYLE_EVENT, DELETE_USER_EVENT, UPDATE_USER_DATA_EVENT, FEEDS_LIST_EVENT, EDIT_USER_EVENT, ADD_POST_EVENT,
  DELETE_PHOTO_EVENT, DELETE_VIDEO_EVENT, UPDATE_POST_EVENT, STATISTIC_DATA_EVENT, SETTINGS_LIST_EVENT,
  SETTING_CREATE_UPDATE_EVENT
}